import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./ui/Navbar";
import Footer from "@/app/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Biuro Podróży Glob",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-full  flex-col flex md:gap">
          <header className=" flex p-4 justify-items-center  md:h-[75px] sticky top-0 z-20 border-b bg-white ">
            <Navbar />
          </header>
          <div className=" overflow-x-hidden flex flex-col  gap-20 2xl:w-full 2xl:h-full 2xl:flex 2xl:flex-col md:w-full md:h-full   2xl:max-h-full  lg:w-full lg:h-full xl:w-full xl:h-full xl:justify-center xl:items-center">
            {" "}
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
